version: "3"

services:
    nodejs:
        image: jwong12/task-manager
        container_name: task-manager-production
        restart: always
        volumes:
            - node_modules:/home/node/app/node_modules
        networks:
            - backend-network
        ports:
            - "8080:3000"
        environment:
            PRODUCTION: 'true'
            
    mongo-db:
        image: mongo:bionic
        container_name: mongodb-taskmanager-prod
        volumes:
            - mongo-data:/app/data
        networks:
            - backend-network
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: jameswong
            MONGO_INITDB_ROOT_PASSWORD: A01025959

networks:
    backend-network:
        driver: bridge

volumes:
    mongo-data: {}
    node_modules: {}
    